package: forcal
version: '5.2.0-beta1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/forcal/issues

page:
    title: 'translate:forcal_title'
    perm: forcal[]
    icon: rex-icon fa-calendar
    block: system
    subpages:
        calendar: { title: 'translate:forcal_calendar', icon: rex-icon fa-calendar }
        entries: { title: 'translate:forcal_entries', icon: rex-icon fa-list-ul }
        categories: { title: 'translate:forcal_categories', icon: rex-icon fa-th-list, perm: forcal[catspage] }
        venues: { title: 'translate:forcal_venues', icon: rex-icon fa-map-marker, perm: forcal[venuespage] }
        user_permissions: { title: 'translate:forcal_user_permissions', icon: rex-icon fa-users, itemclass: pull-right, perm: forcal[userpermissions] }
        settings: { title: 'translate:forcal_settings', icon: rex-icon fa-cog, itemclass: pull-right, perm: forcal[settings] }

requires:
    redaxo: ^5.18.0
    php:
        version: '>=8.1, <9'
        extensions: [intl]
    packages:
        flatpickr: '>=1.1.1'

default_config:
    forcal_multiuser: 1
    forcal_shortcut_save: 1
    forcal_full_time_preselection: 1
    forcal_start_page: 'calendar'

console_commands:
    forcal:list: forCal\Command\ListCommand
