package: forcal
version: '3.6.0'
name: forcal
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/forcal

page:
  title: 'translate:forcal_title'
  perm: forcal[]
  icon: rex-icon fa-calendar
  block: system
  subpages:
    calendar: { title: 'translate:forcal_calendar',perm: 'forcal[]', icon: rex-icon fa-calendar, itemclass: item_calendar }
    entries: { title: 'translate:forcal_entries',perm: 'forcal[]', icon: rex-icon fa-calendar-plus-o, itemclass: item_entries }
    categories: { title: 'translate:forcal_categories',perm: 'forcal[catspage]', icon: rex-icon fa-folder, itemclass: item_categories }
    venues: { title: 'translate:forcal_venues',perm: 'forcal[venuespage]', icon: rex-icon fa-map-marker, itemclass: item_venues }
    settings:
      title: 'translate:forcal_settings'
      perm: forcal[settings]
      icon: rex-icon fa-cogs
      itemclass: pull-right
    help:
      title: 'translate:forcal_help'
      perm: admin[]
      subPath: README.md
      itemclass: pull-right
requires:
  redaxo: '^5.11'
  php:
    version: '>=7.1'
